language: python
sudo: true

warnings_are_errors: false

python:
  - "3.6"
  - "3.7-dev"

services:
  - docker

branches:
  only:
    - master
    - integrator
    - /^release-.*$/

script:
  - .travis/install.sh cimr
  - .travis/build_test.sh
  