language: python
sudo: false
warnings_are_errors: false
python:
  - "3.6"
services:
  - docker
branches:
  only:
  - master
if: branch = master
  script:
    - python setup.py build
    - python setup.py install
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bach ./check_pull_request.sh; fi'
#   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./cimr/; fi'
