language: python
sudo: false
warnings_are_errors: false
python:
  - "3.6"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - python continuous_mr.py
after_success:
  - git checkout master
  - bash update_repo.sh
